name: Test Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Test YTConverter
        shell: cmd
        run: |
          echo Running installer...
          call standalone\install.bat
          
          echo Temporarily updating PATH for this session...
          set PATH=%LocalAppData%\Programs\YTConverter\ffmpeg;%PATH%

          echo Testing yt-dlp...
          yt-dlp --version

          echo Testing ffmpeg...
          ffmpeg -version
